[project]
name = "trpocp-practice-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.4.2",
]


[tool.pytest.ini_options]
pythonpath = ["."]
testpaths   = ["tests"]
addopts     = ["--import-mode=importlib"]